export { AboutPage } from './pages/AboutPage'
export { ContactPage } from './pages/ContactPage'
export { HomePage } from './pages/HomePage'
export { HowItWorksPage } from './pages/HowItWorksPage'
export { PrivacyPage } from './pages/PrivacyPage'
export { TermsPage } from './pages/TermsPage'
