begin;
set local search_path=public,extensions;
select plan(16);
select ok(not has_function_privilege('anon','public.get_tenant_reporting(uuid,integer)','EXECUTE'),'Anonymous users cannot execute the report RPC');
select ok(not has_table_privilege('authenticated','private.tenant_portfolio_snapshots','SELECT'),'History cannot be read outside the authorized report RPC');
select set_config('request.jwt.claim.sub','cccccccc-cccc-4ccc-8ccc-ccccccccccc5',true);
set local role authenticated;
select is(jsonb_array_length(public.get_tenant_reporting('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1',7)->'portfolio'),2,'Insurer sees its own two linked FSPs');
select is(jsonb_array_length(public.get_tenant_reporting('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1',7)->'months'),12,'Twelve monthly reporting slots');
select ok(public.get_tenant_reporting('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1',7)->'months'->0->'portfolio'='null'::jsonb,'Earlier history is explicitly unavailable');
select throws_ok($$select public.get_tenant_reporting('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa2',7)$$,'42501','Insurer access denied','Cross-tenant reporting denied');
select throws_ok($$select public.get_tenant_reporting('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1',2)$$,'22023','Invalid reporting window','Unsupported reporting windows denied');
select throws_ok($$select private.capture_tenant_portfolio('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1')$$,'42501',null,'Browser cannot capture or forge history');
select ok(public.reserve_report_email('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1','fa000000-0000-4000-8000-000000000001'),'First email reservation allowed');
select ok(not public.reserve_report_email('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1','fa000000-0000-4000-8000-000000000001'),'Duplicate email reservation denied');
select public.reserve_report_email('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1',('fa000000-0000-4000-8000-' || lpad(n::text,12,'0'))::uuid) from generate_series(2,5) n;
select ok(not public.reserve_report_email('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1','fa000000-0000-4000-8000-000000000006'),'More than five reports in ten minutes are denied');
select throws_ok($$select public.reserve_report_email('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa2','fa000000-0000-4000-8000-000000000002')$$,'42501','Report email denied','Cross-tenant email denied');
reset role;
select set_config('request.jwt.claim.sub','cccccccc-cccc-4ccc-8ccc-ccccccccccc1',true);
set local role authenticated;
select throws_ok($$select public.get_tenant_reporting('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1',7)$$,'42501','Insurer access denied','An FSP administrator cannot read insurer reports');
reset role;
create temporary table reporting_before as select count(*) as snapshots from private.tenant_portfolio_snapshots where tenant_id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1';
update public.fsps set trade_name=trade_name || ' reporting-test' where id='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbb001';
set constraints all immediate;
select is((select count(*) from private.tenant_portfolio_snapshots where tenant_id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1'),(select snapshots+1 from reporting_before),'A source change automatically captures one portfolio snapshot');
select ok(exists(select 1 from private.tenant_portfolio_snapshots s,jsonb_array_elements(s.portfolio) r where s.id=(select max(id) from private.tenant_portfolio_snapshots where tenant_id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1') and r->>'fspName' like '%reporting-test'),'Captured history contains the changed FSP data');
select ok(exists(select 1 from cron.job where jobname='fsp-dashboard-daily-snapshots' and active),'Daily reporting job is active');
select * from finish();
rollback;
