export { ForgotPasswordPage } from './pages/ForgotPasswordPage'
export { LoginPage } from './pages/LoginPage'
export { RegisterPage } from './pages/RegisterPage'
export { ResetPasswordPage } from './pages/ResetPasswordPage'
export { VerifyPage } from './pages/VerifyPage'
